In [1]:
import numpy as np

# Read the npy file
data = np.load('/nevis/riverside/data/sc5303/sbnd/offline_ad/pi0/npy/larcv_mc_20250805_190855_243056_4eed27d4-ea61-46ef-b402-53c9055ed799.npy')

# Print the content
print(data)

[[0.0000000e+00 1.3560000e+03 1.0200000e+03 5.3100000e+02 1.8555707e-01]
 [0.0000000e+00 1.3560000e+03 1.0210000e+03 5.3100000e+02 1.8555707e-01]
 [0.0000000e+00 1.3560000e+03 1.0220000e+03 5.3100000e+02 4.3978611e-01]
 ...
 [3.1000000e+01 1.4400000e+03 8.2000000e+02 1.3210000e+03 7.8018911e-02]
 [3.1000000e+01 1.5110000e+03 7.6400000e+02 1.4070000e+03 5.7431811e-01]
 [3.1000000e+01 1.5110000e+03 7.6500000e+02 1.4070000e+03 5.4699087e-01]]
